### ISSUE TITLE
Update to 2014.Q3 SP1

### ISSUE THREAD

**Issue by jabas06** [kendo-labs/bower-kendo-ui#17]
Hello,

Any news on when bower package will be updated to 2014.Q3 SP1?

**Comment by codylindley** [comment]
If you look at the tags, it's there. You can get at it. Just use newer version you want when installing with bower.

https://www.dropbox.com/s/wc1zq5z5gikerdz/Screenshot%202015-02-06%2014.49.43.png?dl=0
